spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dw_study?useUnicode=true&charaterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: ljsm0317
    initialization-mode: never
    schema: classpath:init.sql
mybatis:
  mapper-locations: classpath:/sqlmap/sqlmapper_*.xml
  type-aliases-package: com.ljs.board.vo
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
logging.level:
  org.hibernate.SQL: debug
page helper:
  ## helper-dialect:사용하는 데이터 베이스
  helper-dialect: mysql
  ## reasonable: true(0페이지 1페이지, 13페이지까지 있는데 14페이지 요청이 들어오면 13페이지로 리턴해줌)
  reasonable: true
